app/urls.py
from django.conf.urls import url
from django.urls import path,include
from . import views
# from app.views import add_to_cart,mark_order_as_done
urlpatterns=[
    path('',views.home,name="home"),
    path('login',views.login,name='login'),
    path('logout',views.logout,name='logout'),
    path('signup',views.signup,name='signup'),
    path('details',views.details,name='details'),
    path('bin',views.bin,name='bin'),
    path('view_challan',views.view_challan,name='view_challan'),
    path('search', views.search, name="search"),
    path('review',views.review,name='review'),
    path('profile',views.profile,name='profile'),
    path('approved',views.approved,name='approved'),
    path('video_upload',views.video_upload,name='video_upload'),
    path('image_upload',views.image_upload,name='image_upload'),
    path('vid_upload',views.vid_upload,name='vid_upload'),
    path('img_upload',views.img_upload,name='img_upload'),
    path('reject/<int:ids>',views.reject,name='reject'),
    path('approve/<int:ids>',views.approve,name='approve'),
    path('update/<int:ids>',views.update,name='update'),
    path('pdf',views.GeneratePdf,name='pdf'),
    path('blog',views.blog,name='blog'),
    path('aboutus',views.aboutus,name='aboutus'),
]

capstone/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)


#customizing admin text

admin.site.site_header = 'COPVISION'
admin.site.index_title = 'Welcome to project '
admin.site.site_title = 'Control Panel'

app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.timezone import datetime

# Create your models here.

class employee(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	name = models.CharField(max_length=20,default='Employee')
	phone = models.IntegerField(default=0)
	fname = models.CharField(max_length=20,default='fathers name')
	email = models.EmailField(max_length=100,default='abc@gmail.com')
	
class gen_challan(models.Model):
	vehicle_number = models.CharField(max_length=50,default='Number not detected')
	amount = models.IntegerField(default=0)
	faults = models.IntegerField(default=0)
	fault = models.CharField(max_length=50,default='No fault')
	frame_num = models.CharField(max_length=50,default='0')	
	res_img = models.ImageField(upload_to='deploy/videos/%Y/%m/%d/',blank=True,null=True)
	approved = models.BooleanField(default=False)
	rejected = models.BooleanField(default=False)

class upload(models.Model):
	Video_Description= models.CharField(max_length=500)
	timestamp   = models.DateTimeField(auto_now_add=True,blank=True,null=True)
	videofile= models.FileField(upload_to='deploy/videos/%Y/%m/%d/', null=True, verbose_name="")
	numberofframes=models.IntegerField(default=0)

templates/aboutus.html
{% load static %}
<!DOCTYPE html>
<head>
<title>About</title>
</head>

<body background='./static/background.jpg'>
<img src="./static/logo1.png" style="border:none;poition:absolute; top:0px; width:150px;height:170px;float:right">
<h1 style="color:blue; font-family:verdana">About the Project</h1> <b>
<p style="color:green ;font-size:20px ; font-family:verdana"> This project aims to use Machine Learning Technology and basic programming technique to ensure that safety rules are being followed in the country. The two wheelers accidents 
are the most in the country. The automatic detection of breaking of rules and then generating their challan according to present fine can be very useful for traffic regulation.</p>

<p style="color:green ;font-size:20px ; font-family:verdana">The idea is a team of CopVision can use the video recorded at the traffic signals to check if any rule is broken. For a vechicle which has broken the rule, its number plate can
be used to generate E-challans. This problem not only solves the shortage of workforce in traffic police but also implies effective control.</p>
</b>
<div style="position: relative">
                <p style="position: fixed; bottom: 0; width:100%; text-align: left;font-family:Segoe script"> <b>Created by CopVision Team</b> 
                </p>
            </div>
</body>

templates/approved.html
{% load static %}
<!doctype html>
<html lang="en">
<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="generator" content="Jekyll v3.8.5">
  <title>CopVision</title>


  <!-- Bootstrap core CSS -->
  <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,400,300,500,600,700" rel="stylesheet">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'homepage/css/base.css' %}">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Poppins:200,300,400,500,600,700,800&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Amatic+SC:400,700&display=swap" rel="stylesheet">
  <style>
  a { color: #94041c; } /* CSS link color */
  .bd-placeholder-img {
    font-size: 1.125rem;
    text-anchor: middle;
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
  }

  @media (min-width: 768px) {
    .bd-placeholder-img-lg {
      font-size: 3.5rem;
    }
  }
  </style>
  <!-- Custom styles for this template -->
</head>
<body style="background-color:white;">
  <div class="bg">
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark fixed-top p-3 mb-5 bg-dark">

        <a class="navbar-brand" href="{% url 'home' %}">
          <img src="{% static 'logo1.png' %}" width="30" height="30" class="d-inline-block align-top hovernow" style="border-radius:50%;" alt="">
          <span class="title-custom">CopVision</span>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        {% block navitems %}
        <ul class="navbar-nav ml-auto">
          <li><a class="nav-item nav-link" href="{% url 'blog' %}">Official Blog</a></li>
          {% if user.is_authenticated and perms.app.change_challan %}
          <li><a class="nav-item nav-link" href="{% url 'review' %}">Review</a></li>
          <li><a class="nav-item nav-link" href="{% url 'approved' %}">Approved</a></li>
          <li><a class="nav-item nav-link" href="{% url 'bin' %}">Bin</a></li>
          <li><a class="nav-item nav-link" href="{% url 'profile' %}">My Profile</a></li>
          <li><a class="nav-item nav-link" href="javascript:{document.getElementById('logout').submit()}" onclick="">Logout <strong>{{user.username}}</strong></a></li>
          {% elif user.is_authenticated and perms.app.change_upload %}
            <li><a class="nav-item nav-link" href="#">My Profile</a></li>
            <li><a class="nav-item nav-link" href="javascript:{document.getElementById('logout').submit()}" onclick="">Logout <strong>{{user.username}}</strong></a></li>
          {% endif %}
        </ul>
        <form class="" id="logout" action="{% url 'logout' %}" method="post">
          {% csrf_token %}
          <input type="hidden"  value="">
        </form>
        {% endblock navitems %}
          </nav>
      </div>
    </header>
    <div class="container mx-auto " style="padding-bottom:100px;">
      {% block content %}
      {% if error %}
      <div class="alert alert-danger" role="alert">
        {{error.text}}
      </div>
      {% endif %}
      <table class="table">
                <style>
                a { color: #94041c; } /* CSS link color */
                th {
                background-color: #94041c;
                color: white;
                }
                </style>
                <thead class="thead-primary">
                  <tr class="text-center">

                  <th scope="col">Challan No.</th>
                  <th scope="col">Vehicle Number</th>
                  <th scope="col">Faults</th>
                  <th scope="col">Fault</th>                  
                  <th scope="col">Amount</th>                  
                  <th scope="col">Image</th>
                  <th scope="col">Approved</th>                
        </tr>
        </thead>
        <tbody>           
        {% for review in challan %}       
            <tr class="text-center mx-auto cardbody hovernow border border-danger" style="padding:3em;height:100px;margin:3em;">
                <td scope="row">{{ review.id }}</td>
                <td>{{ review.vehicle_number }}</td>
                <td>{{ review.faults }}</td>
                <td>{{ review.fault }}</td>    
                <td>Rs. {{ review.amount }}</td>            
                <td><img src={{ review.res_img }} width="200" height="200"></td>
                <td><a href="{% url 'approve' review.id %}"><i class="fa fa-check"></i></a></td>
            </tr>              
        {% endfor %}
        </tbody>
    </table>

      {% endblock content %}
    </div>
  </div>
    <footer class="footer fixed-bottom">


    <div class="container">

      <div class="row">
          <div class="mouse">
            <a href="#" class="mouse-icon">
              <div class="mouse-wheel"><span class="ion-ios-arrow-up"></span>
              </div>
            </a>
          </div>
        </div>
        <br> <br>
      <div class="row">
        <div class="col-md-12 text-center">
          <p>
            Copyright &copy;<script>document.write(new Date().getFullYear());</script> | Made with &#10084;&#65039; by <a href="{% url 'aboutus' %}" target="_blank">The Copvision Team</a>
          </p>
        </div>
      </div>
    </div>
  </footer>
<script type="text/javascript" src="{% static 'homepage/js/base.js' %}"></script>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
</body>
</html>

templates/bin.html
{% load static %}
<!doctype html>
<html lang="en">
<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="generator" content="Jekyll v3.8.5">
  <title>CopVision</title>


  <!-- Bootstrap core CSS -->
  <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,400,300,500,600,700" rel="stylesheet">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'homepage/css/base.css' %}">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Poppins:200,300,400,500,600,700,800&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Amatic+SC:400,700&display=swap" rel="stylesheet">
  <style>
  a { color: #94041c; } /* CSS link color */
  .bd-placeholder-img {
    font-size: 1.125rem;
    text-anchor: middle;
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
  }

  @media (min-width: 768px) {
    .bd-placeholder-img-lg {
      font-size: 3.5rem;
    }
  }
  </style>
  <!-- Custom styles for this template -->
</head>
<body style="background-color:white;">
  <div class="bg">
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark fixed-top p-3 mb-5 bg-dark">

        <a class="navbar-brand" href="{% url 'home' %}">
          <img src="{% static 'logo1.png' %}" width="30" height="30" class="d-inline-block align-top hovernow" style="border-radius:50%;" alt="">
          <span class="title-custom">CopVision</span>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        {% block navitems %}
        <ul class="navbar-nav ml-auto">
          <li><a class="nav-item nav-link" href="{% url 'blog' %}">Official Blog</a></li>
          {% if user.is_authenticated and perms.app.change_challan %}
          <li><a class="nav-item nav-link" href="{% url 'review' %}">Review</a></li>
          <li><a class="nav-item nav-link" href="{% url 'approved' %}">Approved</a></li>
          <li><a class="nav-item nav-link" href="{% url 'bin' %}">Bin</a></li>
          <li><a class="nav-item nav-link" href="{% url 'profile' %}">My Profile</a></li>
          <li><a class="nav-item nav-link" href="javascript:{document.getElementById('logout').submit()}" onclick="">Logout <strong>{{user.username}}</strong></a></li>
          {% elif user.is_authenticated and perms.app.change_upload %}
            <li><a class="nav-item nav-link" href="#">My Profile</a></li>
            <li><a class="nav-item nav-link" href="javascript:{document.getElementById('logout').submit()}" onclick="">Logout <strong>{{user.username}}</strong></a></li>
          {% endif %}
        </ul>
        <form class="" id="logout" action="{% url 'logout' %}" method="post">
          {% csrf_token %}
          <input type="hidden"  value="">
        </form>
        {% endblock navitems %}
          </nav>
      </div>
    </header>
    <div class="container mx-auto " style="padding-bottom:100px;">
      {% block content %}
      {% if error %}
      <div class="alert alert-danger" role="alert">
        {{error.text}}
      </div>
      {% endif %}
      <table class="table">
                <style>
                a { color: #94041c; } /* CSS link color */
                th {
                background-color: #94041c;
                color: white;
                }
                </style>
                <thead class="thead-primary">
                  <tr class="text-center">

                  <th scope="col">Challan No.</th>
                  <th scope="col">Vehicle Number</th>
                  <th scope="col">Faults</th>
                  <th scope="col">Fault</th>                  
                  <th scope="col">Image</th>                  
                  <th scope="col">Restore</th>
        </tr>
        </thead>
        <tbody>           
        {% for review in challan %}       
            <tr class="text-center mx-auto cardbody hovernow border border-danger" style="padding:3em;height:100px;margin:3em;">
                <td scope="row">{{ review.id }}</td>
                <td>{{ review.vehicle_number }}</td>
                <td>{{ review.faults }}</td>
                <td>{{ review.fault }}</td>                
                <td><img src={{ review.res_img }} width="200" height="200"></td>
                <td><a href="{% url 'reject' review.id %}"><i class="fa fa-check"></i></a></td>                    
            </tr>              
        {% endfor %}
        </tbody>
    </table>

      {% endblock content %}
    </div>
  </div>
    <footer class="footer fixed-bottom">


    <div class="container">

      <div class="row">
          <div class="mouse">
            <a href="#" class="mouse-icon">
              <div class="mouse-wheel"><span class="ion-ios-arrow-up"></span>
              </div>
            </a>
          </div>
        </div>
        <br> <br>
      <div class="row">
        <div class="col-md-12 text-center">
          <p>
            Copyright &copy;<script>document.write(new Date().getFullYear());</script> | Made with &#10084;&#65039; by <a href="{% url 'aboutus' %}" target="_blank">The Copvision Team</a>
          </p>
        </div>
      </div>
    </div>
  </footer>
<script type="text/javascript" src="{% static 'homepage/js/base.js' %}"></script>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
</body>
</html>

templates/details.html
{% load static %}
<!doctype html>
<html lang="en">
<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="generator" content="Jekyll v3.8.5">
  <title>CopVision</title>


  <!-- Bootstrap core CSS -->
  <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,400,300,500,600,700" rel="stylesheet">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'homepage/css/base.css' %}">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Poppins:200,300,400,500,600,700,800&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Amatic+SC:400,700&display=swap" rel="stylesheet">
  <style>
  a { color: #94041c; } /* CSS link color */
  .bd-placeholder-img {
    font-size: 1.125rem;
    text-anchor: middle;
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
  }

  @media (min-width: 768px) {
    .bd-placeholder-img-lg {
      font-size: 3.5rem;
    }
  }
  </style>
  <!-- Custom styles for this template -->
</head>
<body style="background-color:white;">
  <div class="bg">
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark fixed-top p-3 mb-5 bg-dark">

        <a class="navbar-brand" href="{% url 'home' %}">
          <img src="{% static 'logo1.png' %}" width="30" height="30" class="d-inline-block align-top hovernow" style="border-radius:50%;" alt="">
          <span class="title-custom">CopVision</span>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        {% block navitems %}
        <ul class="navbar-nav ml-auto">
          <li><a class="nav-item nav-link" href="{% url 'blog' %}">Official Blog</a></li>
          {% if user.is_authenticated and perms.app.change_challan %}
          <li><a class="nav-item nav-link" href="{% url 'review' %}">Review</a></li>
          <li><a class="nav-item nav-link" href="{% url 'approved' %}">Approved</a></li>
          <li><a class="nav-item nav-link" href="{% url 'bin' %}">Bin</a></li>
          <li><a class="nav-item nav-link" href="{% url 'profile' %}">My Profile</a></li>
          <li><a class="nav-item nav-link" href="javascript:{document.getElementById('logout').submit()}" onclick="">Logout <strong>{{user.username}}</strong></a></li>
          {% elif user.is_authenticated and perms.app.change_upload %}
            <li><a class="nav-item nav-link" href="#">My Profile</a></li>
            <li><a class="nav-item nav-link" href="javascript:{document.getElementById('logout').submit()}" onclick="">Logout <strong>{{user.username}}</strong></a></li>
          {% endif %}
        </ul>
        <form class="" id="logout" action="{% url 'logout' %}" method="post">
          {% csrf_token %}
          <input type="hidden"  value="">
        </form>
        {% endblock navitems %}
          </nav>
      </div>
    </header>
    <div class="container mx-auto " style="padding-bottom:100px;">
      {% block content %}
      {% if error %}
      <div class="alert alert-danger" role="alert">
        {{error.text}}
      </div>
      {% endif %}
      <div class="mx-auto jumbotron hovernow border border-danger" style="padding:2em;width:370px; height:400px;margin:2em;">
        <h1>Fill Details</h1>
        <form method="POST" action="{% url 'details' %}" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="form-group">
            Name:
            <br>
            <input type="text" name="nam" value="">
          </div>
          <div class="form-group">
            Father's Name:
            <br>
            <input type="text" name="fnam" value="">
          </div>
          <div class="form-group">
            Email:
            <br>
            <input type="email" name="email" placeholder="abc@thapar.edu">
          </div>
          <div class="form-group">
            Phone:
            <br>
            <input type="text" name="phone" value="">
          </div>
  <!-- <div class="form-group">
    Balance:
    <input class="form-control" type="text" placeholder="0" readonly>
  </div> -->
  <input type="submit" name="submit" value="Save details">
</form>
      </div> 

      {% endblock content %}
    </div>
  </div>
    <footer class="footer fixed-bottom">


    <div class="container">

      <div class="row">
          <div class="mouse">
            <a href="#" class="mouse-icon">
              <div class="mouse-wheel"><span class="ion-ios-arrow-up"></span>
              </div>
            </a>
          </div>
        </div>
        <br> <br>
      <div class="row">
        <div class="col-md-12 text-center">
          <p>
            Copyright &copy;<script>document.write(new Date().getFullYear());</script> | Made with &#10084;&#65039; by <a href="{% url 'aboutus' %}" target="_blank">The Copvision Team</a>
          </p>
        </div>
      </div>
    </div>
  </footer>
<script type="text/javascript" src="{% static 'homepage/js/base.js' %}"></script>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
</body>
</html>